### PR TITLE
Version 6.1, An Elegy for Faded Moonlight

### LINKED ISSUE #11: The calc page crashes when switching artifictions in certain situations (a set with set2 effect config to a set with set4 effect config)
**Description:**

The calc page crashes if the target set has a 4-piece effect config but a 2-piece config is on page.

---

**Steps to Reproduce:**

1. Open the calc page.
2. Select an artifiction set with a 2-piece effect config.
3. Switch to another set that has a 4-piece effect config.
4. Observe the crash.

---

**Expected Behavior:**
The calc page should apply the new effect config without crashing.

---

**Actual Behavior:**
The page crashes immediately and reloads.
Console output shows:

```
TypeError: Cannot read properties of null (reading 'config_night_of_the_skys_unveiling')
    at fe.fn (835.a620e197.js:1:8392)
    at fe.run (vue.global.prod.js:1:5560)
    at get value (vue.global.prod.js:1:13767)
    at fe.fn (artifact-plan-page.45713cce.js:1:82007)
    at fe.run (vue.global.prod.js:1:5560)
    at get value (vue.global.prod.js:1:13767)
    at fe.fn (artifact-plan-page.45713cce.js:1:82161)
    at fe.run (vue.global.prod.js:1:5560)
    at get value (vue.global.prod.js:1:13767)
    at Et (vue.global.prod.js:1:12762)
```

**Environment:**

* OS: Windows 11
* Browser: Edge 141.0.0.0
* Version: V6.0.0

### LINKED ISSUE #12: 首页的yas项目和圣遗物扫描中的椰羊扫描器均已过时
如题

### PR DESCRIPTION
**Pull request by 2745518585**
#### Features

- Yas for Version 6.1 (Resolves #12)
- Artificts data format Version 2 that enable importing and exporting artifacts sets
- Criticalable healing
- New implementation of artifact configs **(Experimental)** (Resolves #11)
- Global configs **(Experimental)**
- Reordered buffs according to characters archive

#### Features for version 6.1

**Characters:**

- Nefer 奈芙尔

**Weapons:**

- Reliquary of Truth 真语秘匣
- Dawning Frost 霜辰
- Sacrificer's Staff 圣祭者的辉杖

**Buffs:**

- Lauma-Runo: Dawnless Rest of Karsikko 菈乌玛-「圣言述咏·终宵永眠」
- Lauma-Pale Hymn 菈乌玛-「苍色祷歌」
- Lauma-Runo-Light for the Frosty Night 菈乌玛-「奉向霜夜的明光」
- Lauma-Moonsign Benediction: Nature's Chorus 菈乌玛-「月兆祝赐·千籁恩宠」
- Flins-Moonsign Benediction: Old World Secrets 菲林斯-「月兆祝赐·旧世潜藏」
- Nefer-Moonsign Benediction: Old World Secrets 奈芙尔-「月兆祝赐·廊下暮影」
- Nightweaver's Looking Glass-Millennial Hymn 纺夜天镜-「千年的祷咏歌」

#### Changes

- Remove buff Lauma-Evermoon's Sacrament Song

#### Features before version 6.1

**Characters:**

- Aether-Anemo 空-风
- Lumine-Anemo 荧-风
- Aether-Geo 空-岩
- Lumine-Geo 荧-岩
- Aether-Electro 空-雷
- Lumine-Electro 荧-雷
- Aether-Dendro 空-草
- Lumine-Dendro 荧-草
- Aether-Hydro 空-水
- Lumine-Hydro 荧-水
- Aether-Pyro 空-火
- Lumine-Pyro 荧-火

**Target Functions:**

- Aether-Pyro-Traveller 空-火-旅行者
- Lumine-Pyro-Traveller 荧-火-旅行者

**Buffs:**

- Aether-Anemo-Intertwined Winds 空-风-「纠缠的信风」
- Lumine-Anemo-Intertwined Winds 荧-风-「纠缠的信风」
- Aether-Geo-Invincible Stonewall 空-岩-「巍然的青岩」
- Lumine-Geo-Invincible Stonewall 荧-岩-「巍然的青岩」
- Aether-Electro-Violet Vehemence 空-雷-「震怒的苍雷」
- Lumine-Electro-Violet Vehemence 荧-雷-「震怒的苍雷」
- Aether-Dendro-Verdant Overgrowth 空-草-「蔓生的埜草」
- Lumine-Dendro-Verdant Overgrowth 荧-草-「蔓生的埜草」
- Aether-Dendro-Withering Aggregation 空-草-「蕴思的霜草」
- Lumine-Dendro-Withering Aggregation 荧-草-「蕴思的霜草」
- Aether-Pyro-Starfire's Flowing Light 空-火-「流光的星火」
- Lumine-Pyro-Starfire's Flowing Light 荧-火-「流光的星火」
- Aether-Pyro-Ever-Lit Candle 空-火-「长明的烛火」
- Lumine-Pyro-Ever-Lit Candle 荧-火-「长明的烛火」
- Amber-Wildfire 安柏-「疾如野火」
- Barbara-Vitality Burst 芭芭拉-「元气迸发」
- Kirara-Countless Sights to See 绮良良-「沿途百景会心」
- Collei-Gift of the Woods 柯莱-「骞林馈遗」
- Yaoyao-Adeptus' Tutelage 瑶瑶-「妙受琼阁」
- Layla-Starry Illumination 莱依拉-「星示昭明」
- Lynette-Sophisticated Synergy 琳妮特-「巧施协同」
- Chevreuse-Vanguard's Coordinated Tactics 夏沃蕾-「尖兵协同战法」
- Chevreuse-Vertical Force Coordination 夏沃蕾-「纵阵武力统筹」
- Chevreuse-In Pursuit of Ending Evil 夏沃蕾-「终结罪恶的追缉」
- Sethos-Beneficent Plumage 赛索斯-「真念鸵羽集」
- Ororon-Ode to Deep Springs 欧洛伦-「致深泉的颂赞」
- Lan Yan-"With Drakefalcon's Blood-Pearls Adorned" 蓝砚-「『揽龙鹰兮结血珠』」
- Iansan-The Three Principles of Power 伊安珊-「力的三原理」
- Iansan-Laziness is the Enemy! 伊安珊-「偷懒是健身大忌!」
- Iansan-Teachings of the Collective of Plenty 伊安珊-「『沃陆之邦』的训教」
- Ifa-Rescue Essentials 伊法-「救援要义」

#### Fixes

- Escoffier
- Skirk
- Moonsign buffs of Lauma 
- Double count of Gleaming Moon Effect
- Wrong name of buff Kaveh-Painted Dome ('Kaveh Q' before)

### CODE REVIEW

File: src/utils/common.js [hunk 1]
```diff
@@ -20,13 +20,32 @@ export function deepCopy(obj) {
...
+}
+
 export function convertArtifact(art) {
     let temp = {
         position: art.position,
         setName: art.setName,
         primary: {},
         secondary: {},
-        refer: art,
+        Nefer: art,
```
[the remark this answers is not in the document]
Comment (2745518585) [reply src/utils/common.js]: fixed in #[46d3821](https://github.com/Sukwants/genshin_artifact/pull/13/commits/46d382192920822f4dfcca7d8df4d04c8732257d)

File: mona_core/src/character/characters/traveller/mod.rs
Comment (Sukwants) [inline mona_core/src/character/characters/traveller/mod.rs]: I wonder why Aether & Lumine as characters are in the directory `traveller`, while the buffs they offer are not.

File: src/images/characters/AetherAnemo_splash_old.webp
Comment (Sukwants) [inline src/images/characters/AetherAnemo_splash_old.webp]: It seems that Aether is splited into six individuals, and they all possess pyro power.

So is Lumine.

And so simple the splash photo is.

File: mona_core/src/character/characters/traveller/mod.rs
Comment (2745518585) [reply mona_core/src/character/characters/traveller/mod.rs]: This is a historic problem.
